---
apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: sno-2
  namespace: sno-2
spec:
  baseDomain: faredge.lab 
  clusterName: sno-2
  controlPlaneConfig:
    servingCertificates: {}
  clusterInstallRef:
    group: extensions.hive.openshift.io
    kind: AgentClusterInstall
    name: sno-2
    version: v1beta1
  platform:
    agentBareMetal: 
      agentSelector:
        matchLabels:
          cluster-name: "mgmt-spoke1-sno-2"
  pullSecretRef:
    name: assisted-deployment-pull-secret-sno-2
