---
apiVersion: v1
kind: Namespace
metadata:
  name: ztp-clusters
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: open-cluster-management:subscription-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: open-cluster-management:subscription-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: kube:admin
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: system:admin
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: ztp-repository
  namespace: ztp-clusters
spec:
  type: Git
  pathname: http://dummy:dummy@[2000:3220:1099::11]:3000/faredge-ztp/faregde-ztp.git
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: local-cluster-placement
  namespace: ztp-clusters
  annotations: {}
  labels:
    app: cluster-deployments
spec:
  clusterSelector:
    matchLabels:
      local-cluster: 'true'
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: acm-prereqs-subscription
  namespace: ztp-clusters 
  annotations:
    apps.open-cluster-management.io/git-branch: master
    apps.open-cluster-management.io/git-path: acm-prereqs/
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: acm-prereqs
    app.kubernetes.io/part-of: acm-prereqs
spec:
  channel: ztp-clusters/ztp-repository
  placement:
    placementRef:
      name: local-cluster-placement
      kind: PlacementRule
