---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "group-du-sno"
  namespace: "group-du-sno"
  labels:
    test: true
spec:
  bindingRules:
    group-du-sno: ""
  mcp: "master"
  sourceFiles:
    ## PAO
    - fileName: PaoSubscriptionNS.yaml
      policyName: "pao-deployment"
    - fileName: PaoSubscriptionOperGroup.yaml
      policyName: "pao-deployment"
    - fileName: PaoSubscription.yaml
      policyName: "pao-deployment"
      spec:
        channel: "4.8"
        name: performance-addon-operator
        source: redhat-operator-index
    ## PTP
    - fileName: MachineConfigDisableChronyd.yaml
      policyName: "ptp-operator-deployment"
    - fileName: PtpSubscriptionNS.yaml
      policyName: "ptp-operator-deployment"
    - fileName: PtpSubscriptionOperGroup.yaml
      policyName: "ptp-operator-deployment"
    - fileName: PtpSubscription.yaml
      policyName: "ptp-operator-deployment"
      spec:
        channel: "4.8"
        name: ptp-operator
        source: redhat-operator-index
    - fileName: PtpConfigSlave.yaml
      policyName: "ptp-config-slave-subscription"
      metadata:
        name: "fe-ptp-slave"
      spec:
        profile:
        - name: "slave"
          interface: "ens1f0"
          ptp4lOpts: "-s -2 --summary_interval -4"
          phc2sysOpts: "-a -r -n 24"
          ptp4lConf: |
            [global]
            #
            # Default Data Set
            # test
            twoStepFlag 1
            slaveOnly 0
            priority1 128
            priority2 90
            # VZN = 128

            domainNumber 24
            #utc_offset 37
            clockClass 248
            # VZN = 255
            #
            clockAccuracy 0xFE
            offsetScaledLogVariance 0xFFFF
            free_running 0
            freq_est_interval 1
            dscp_event 0
            dscp_general 0
            dataset_comparison ieee1588
            # VZN = G.8275.x

            G.8275.defaultDS.localPriority 200
            #
            # Port Data Set
            #
            logAnnounceInterval -3
            logSyncInterval -4
            logMinDelayReqInterval -4
            logMinPdelayReqInterval -4
            announceReceiptTimeout 3
            syncReceiptTimeout 0
            delayAsymmetry 0
            fault_reset_interval -128
            # VZN = 0

            neighborPropDelayThresh 20000000
            masterOnly 0
            G.8275.portDS.localPriority 200
            #
            # Run time options
            #
            assume_two_step 0
            logging_level 6
            path_trace_enabled 0
            follow_up_info 0
            hybrid_e2e 0
            inhibit_multicast_service 0
            net_sync_monitor 0
            tc_spanning_tree 0
            tx_timestamp_timeout 1000
            # VZN production = 50

            unicast_listen 0
            unicast_master_table 0
            unicast_req_duration 3600
            use_syslog 1
            verbose 0
            summary_interval -4
            # VZN = 6

            kernel_leap 1
            check_fup_sync 0
            #
            # Servo Options
            #
            pi_proportional_const 0.0
            pi_integral_const 0.0
            pi_proportional_scale 0.0
            pi_proportional_exponent -0.3
            pi_proportional_norm_max 0.7
            pi_integral_scale 0.0
            pi_integral_exponent 0.4
            pi_integral_norm_max 0.3
            step_threshold 0.0
            first_step_threshold 0.00002
            max_frequency 900000000
            clock_servo pi
            # VZN = linreg

            sanity_freq_limit 200000000
            ntpshm_segment 0
            #
            # Transport options
            #
            transportSpecific 0x0
            ptp_dst_mac 01:1B:19:00:00:00
            p2p_dst_mac 01:80:C2:00:00:0E
            udp_ttl 1
            udp6_scope 0x0E
            uds_address /var/run/ptp4l
            #
            # Default interface options
            #
            clock_type OC
            #network_transport UDPv4
            network_transport L2
            delay_mechanism E2E
            time_stamping hardware
            tsproc_mode filter
            delay_filter moving_median
            delay_filter_length 10
            egressLatency 0
            ingressLatency 0
            boundary_clock_jbod 0
            # This setting is 1 in VZN config
            #

            #
            # Clock description
            #
            productDescription ;;
            revisionData ;;
            manufacturerIdentity 00:00:00
            userDescription ;
            timeSource 0xA0
    ## SRIOV
    - fileName: SriovSubscriptionNS.yaml
      policyName: "sriov-operator-deployment"
    - fileName: SriovSubscriptionOperGroup.yaml
      policyName: "sriov-operator-deployment"
    - fileName: SriovSubscription.yaml
      policyName: "sriov-operator-deployment"
      spec:
        channel: "4.8"
        name: sriov-network-operator
        source: redhat-operator-index
        sourceNamespace: openshift-marketplace
    - fileName: SriovOperatorConfig.yaml
      policyName: "sriov-operator-deployment"
      spec:
        enableInjector: true
        enableOperatorWebhook: true
        configDaemonNodeSelector:
          "node-role.kubernetes.io/master": ""
        disableDrain: true
    ## SRIOV FEC
    - fileName: SriovSubscriptionNS.yaml
      policyName: "sriov-fec-operator-deployment"
      metadata:
        name: vran-acceleration-operators
    - fileName: SriovSubscriptionOperGroup.yaml
      policyName: "sriov-fec-operator-deployment"
      metadata:
        name: vran-operators
        namespace: vran-acceleration-operators
      spec:
        targetNamespaces:
        - vran-acceleration-operators
    - fileName: SriovSubscription.yaml
      policyName: "sriov-fec-operator-deployment"
      metadata:
        name: sriov-fec-subscription
        namespace: vran-acceleration-operators
      spec:
        channel: "stable"
        name: sriov-fec
        source: certified-operator-index
    ## TODO: We still need to add the SRIOV-FEC Config
    - fileName: MachineConfigDummy.yaml
      policyName: "mc-icsp-tags"
      metadata:
        labels:
          machineconfiguration.openshift.io/role: master
        name: 98-icsp-mirror-digest-only-patch
      spec:
        config:
          ignition:
            version: 3.2.0
          storage:
            files:
            - contents:
                source: 'data:text/plain;charset=utf-8;base64,W1tyZWdpc3RyeV1dCiAgcHJlZml4ID0gIiIKICBsb2NhdGlvbiA9ICJyZWdpc3RyeS5jb25uZWN0LnJlZGhhdC5jb20vaW50ZWwvbjMwMDAtbGFiZWxlciIKICBtaXJyb3ItYnktZGlnZXN0LW9ubHkgPSBmYWxzZQoKICBbW3JlZ2lzdHJ5Lm1pcnJvcl1dCiAgICBsb2NhdGlvbiA9ICJibS1jbHVzdGVyLTEtaHlwZXIuZTJlLmJvcy5yZWRoYXQuY29tOjUwMDAvb2xtL24zMDAwLWxhYmVsZXIiCgpbW3JlZ2lzdHJ5XV0KICBwcmVmaXggPSAiIgogIGxvY2F0aW9uID0gInJlZ2lzdHJ5LmNvbm5lY3QucmVkaGF0LmNvbS9pbnRlbC9zcmlvdi1mZWMtZGFlbW9uIgogIG1pcnJvci1ieS1kaWdlc3Qtb25seSA9IGZhbHNlCgogIFtbcmVnaXN0cnkubWlycm9yXV0KICAgIGxvY2F0aW9uID0gImJtLWNsdXN0ZXItMS1oeXBlci5lMmUuYm9zLnJlZGhhdC5jb206NTAwMC9vbG0vc3Jpb3YtZmVjLWRhZW1vbiIKCltbcmVnaXN0cnldXQogIHByZWZpeCA9ICIiCiAgbG9jYXRpb24gPSAicmVnaXN0cnkucmVkaGF0LmlvL29wZW5zaGlmdDQvb3NlLXNyaW92LW5ldHdvcmstZGV2aWNlLXBsdWdpbiIKICBtaXJyb3ItYnktZGlnZXN0LW9ubHkgPSBmYWxzZQoKICBbW3JlZ2lzdHJ5Lm1pcnJvcl1dCiAgICBsb2NhdGlvbiA9ICJibS1jbHVzdGVyLTEtaHlwZXIuZTJlLmJvcy5yZWRoYXQuY29tOjUwMDAvb2xtL29wZW5zaGlmdDQtb3NlLXNyaW92LW5ldHdvcmstZGV2aWNlLXBsdWdpbiIK'
              filesystem: root
              mode: 420
              path: /etc/containers/registries.conf.d/98-master-mirror-by-digest-registries.conf
    - fileName: MachineConfigDisableChronyd.yaml
      policyName: "mc-rt-ostree-patch"
      metadata:
        labels:
          machineconfiguration.openshift.io/role: master
          test: true
        name: 99-patch-rt-kernel
      spec:
        config:
          ignition:
            version: 3.2.0
          systemd:
            units:
            - name: update-rt-kernel.service
              enabled: true
              contents: |
                [Unit]
                Description=Upgrade kernel to Patched RT
                Wants=network-online.target
                After=network-online.target ignition-firstboot-complete.service
                [Service]
                Type=oneshot
                ExecStart=/bin/bash -c "KVER=4.18.0-305.21.1.rt7.93.el8_4.x86_64 ;\
                  if [[ $(uname -r) != $KVER ]]; then \
                  WS=http://bm-cluster-1-hyper.e2e.bos.redhat.com/rt-kernel ;\
                  rpm-ostree override remove kernel{,-core,-modules,-modules-extra} --install $WS/kernel-rt-core-4.18.0-305.21.1.rt7.93.el8_4.x86_64.rpm  --install $WS/kernel-rt-modules-4.18.0-305.21.1.rt7.93.el8_4.x86_64.rpm --install $WS/kernel-rt-modules-extra-4.18.0-305.21.1.rt7.93.el8_4.x86_64.rpm --install $WS/kernel-rt-modules-internal-4.18.0-305.21.1.rt7.93.el8_4.x86_64.rpm ;\
                  systemctl reboot ;\
                  else echo RT Kernel $KVER already installed; exit 0; fi"
                [Install]
                WantedBy=multi-user.target
