---
apiVersion: v1
kind: Secret
metadata:
  name: assisted-deployment-pull-secret
  namespace: open-cluster-management
stringData:
  .dockerconfigjson: '{"auths":{"bm-cluster-1-hyper.e2e.bos.redhat.com:5000":{"auth":"ZHVtbXk6ZHVtbXk="}}}'
  type: kubernetes.io/dockerconfigjson
